In [1]:
i = 5
while i > 0: # We can write this as 'while i:' because 0 is False!
    i -= 1
    print 'loop {0} . {0} more to go'.format(i,i)

loop 4 . 4 more to go
loop 3 . 3 more to go
loop 2 . 2 more to go
loop 1 . 1 more to go
loop 0 . 0 more to go


In [2]:
for i in range(5):
    print 'I am looping! I have looped {0} times!'.format(i + 1)

I am looping! I have looped 1 times!
I am looping! I have looped 2 times!
I am looping! I have looped 3 times!
I am looping! I have looped 4 times!
I am looping! I have looped 5 times!


In [3]:
for i in range(12):
    print 'loop {0}'.format(i + 1)

loop 1
loop 2
loop 3
loop 4
loop 5
loop 6
loop 7
loop 8
loop 9
loop 10
loop 11
loop 12


In [4]:
my_list = {'cats', 'dogs', 'lizards', 'cows', 'bats', 'sponges', 'humans'} # Lists all the animals in the world
mammal_list = {'cats', 'dogs', 'cows', 'bats', 'humans'} # Lists all the mammals in the world
my_new_list = set()
for animal in my_list:
    if animal in mammal_list:
        # This adds any animal that is both in my_list and mammal_list to my_new_list
        my_new_list.add(animal)
        
print my_new_list

set(['cows', 'bats', 'cats', 'humans', 'dogs'])


In [5]:
i = 10
while True:
    if i == 14:
        break
    i += 1 # This is shorthand for i = i + 1. It increments i with each iteration.
    print i

11
12
13
14


In [6]:
i = 9
while True:
    if i == 15:
        break
    i += 2
    print i

11
13
15


In [7]:
i = 2
print i

2


In [8]:
for i in range(12):
    if i == 4:
        break
    print i

    

0
1
2
3


In [9]:
i = 0
while i < 5:
    i += 1
    if i == 3:
        continue
    print i

1
2
4
5


In [10]:
i = 5
while i < 12:
    i += 1
    if i < 9:   
        continue
    print i  

9
10
11
12


In [11]:
def steve():
    x = [1,2,1,2,1,2,1,1]
    print x

In [12]:
steve()

[1, 2, 1, 2, 1, 2, 1, 1]


In [13]:
def multiply_by_five(x):
    """ Multiplies an input number by 5 """
    return x * 5

n = 4
print n
print multiply_by_five(n)

4
20


In [14]:
def sum_values(*args):
    sum_val = 0
    for i in args:
        sum_val += i
    return sum_val

In [15]:
sum_values()

0

In [16]:
sum_values(steve())

[1, 2, 1, 2, 1, 2, 1, 1]


TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

In [ ]:
print sum_values(1, 2, 3)
print sum_values(10, 20, 30, 40, 50)
print sum_values(4, 2, 5, 1, 10, 249, 25, 24, 13, 6, 4)

In [ ]:
sum_values(1,4,5,7)

In [17]:
def stevemoors(*args):
    sum_val = 0
    for i in args:
        sum_val += i
    return sum_val
    

In [18]:
stevemoors(1,2,1)

4

In [19]:
def point_maker(x, y):
    """ Groups x and y values into a point, technically a tuple """
    return x, y

In [20]:
point_maker(2,2)

(2, 2)

In [21]:
x = (2,2)

In [22]:
print x

(2, 2)


In [23]:
a = point_maker(0, 10)
b = point_maker(5, 3)
def calculate_slope(point_a, point_b):
    """ Calculates the linear slope between two points """
    return (point_b[1] - point_a[1])/(point_b[0] - point_a[0])
print "The slope between a and b is {0}".format(calculate_slope(a, b))

The slope between a and b is -2


In [24]:
c = point_maker(12, 4)
d = point_maker(20, 6)

In [25]:
print c
print d


(12, 4)
(20, 6)


In [26]:
calculate_slope(d, c)

0

In [27]:
calculate_slope(a, b)

-2

In [28]:
e = point_maker(0, 0)

In [29]:
f = point_maker(1, 2)

In [30]:
calculate_slope(e, f)

2

In [31]:
import numpy as np
import matplotlib.pyplot as plt

In [32]:
stock_list = [3.5, 4.7, 7.9, 1.2, 33.3]

In [33]:
returns = np.array(stock_list)

In [34]:
print returns

[  3.5   4.7   7.9   1.2  33.3]


In [35]:
print returns

[  3.5   4.7   7.9   1.2  33.3]


In [36]:
matrix = np.array([[1, 2],[2,4],[8,9]])

In [37]:
print matrix

[[1 2]
 [2 4]
 [8 9]]


In [38]:
print matrix.shape

(3, 2)


In [39]:
print returns

[  3.5   4.7   7.9   1.2  33.3]


In [40]:
print returns[0]

3.5


In [41]:
print returns[0], returns[len(returns)-1]

3.5 33.3


In [42]:
print returns[0:4]

[ 3.5  4.7  7.9  1.2]


In [43]:
print matrix[2, :]

[8 9]


In [44]:
print matrix[2,0]

8


In [45]:
print np.log(returns)

[ 1.25276297  1.54756251  2.06686276  0.18232156  3.5055574 ]


In [46]:
print np.mean(returns)

10.12


In [47]:
print np.max(returns)

33.3


In [48]:
print np.min(returns)

1.2


In [49]:
max_returns = np.max(returns)

In [50]:
min_returns = np.min(returns)

In [51]:
range_returns = max_returns - min_returns

In [52]:
print range_returns

32.1


In [53]:
std = np.std(returns)

In [54]:
print std

11.7898939775


In [55]:
print returns

[  3.5   4.7   7.9   1.2  33.3]


In [56]:
print np.mean(returns)

10.12


In [57]:
print returns*12 + 2

[  44.    58.4   96.8   16.4  401.6]


In [58]:
N = 10
assets = np.zeros((N, 100))
returns = np.zeros((N, 100))

In [59]:
print assets

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0. 

In [60]:
print returns

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0. 

In [61]:
R_1 = np.random.normal(1.01, 0.03, 100)
returns[0] = R_1
assets[0] = np.cumprod(R_1)

In [62]:
print returns

[[ 1.00122304  0.98785594  1.05145122  0.99545202  1.07958946  1.03485113
   0.97229152  1.01705873  1.0267756   1.13883923  1.05186131  1.02049607
   0.99322892  1.0280806   1.02803112  1.03788304  1.05030574  0.9783777
   0.97624952  1.02997453  0.9848724   1.0579588   0.99575206  1.05441687
   0.9895472   1.05105951  1.00368203  1.01123881  1.01996373  0.96641677
   0.99222238  1.00579898  1.02043874  1.03829874  1.01755094  1.03969782
   0.99037095  1.0129888   0.99823191  1.05067991  0.99954297  0.98998202
   0.98422363  1.02125518  0.98431827  1.01093905  1.03315443  1.00750437
   1.03098388  1.01269076  0.9995646   1.00432744  1.02097312  1.03291402
   0.99759962  1.07153391  1.00631023  1.01914354  0.98652323  1.03997609
   0.96867379  1.01241304  0.9980152   1.00161765  1.00707145  1.02653915
   1.01575746  0.98458643  0.99390534  1.00443507  0.99446762  0.96864851
   1.03251216  0.98774966  1.03427494  0.99796041  0.97370739  1.04175586
   0.97134925  1.00413199  0.96823102  

In [63]:
# Generate assets that are correlated with R_1
for i in range(1, N):
    R_i = R_1 + np.random.normal(0.001, 0.02, 100)
    returns[i] = R_i # Set each row of returns equal to the new R_i array
    assets[i] = np.cumprod(R_i)
    
mean_returns = [(np.mean(R) - 1)*100 for R in returns]
return_volatilities = [np.std(R) for R in returns]

In [64]:
plt.bar(np.arange(len(mean_returns)), mean_returns)
plt.xlabel('Stock')
plt.ylabel('Returns')
plt.title('Returns for {0} Random Assets'.format(N));

In [65]:
%matplotlib inline  

In [68]:
N = 2
assets = np.zeros((N, 100))
returns = np.zeros((N, 100))

In [69]:
print assets

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [70]:
R_1 = np.random.normal(1.01, 0.03, 100)
returns[0] = R_1
assets[0] = np.cumprod(R_1)

In [71]:
print assets[0]

[ 1.01132765  1.04061245  1.04390897  1.06617053  1.04767705  1.02210849
  1.03557293  1.08021557  1.05262705  1.06835447  1.06664825  1.11299298
  1.13920165  1.1812998   1.19041108  1.20846908  1.27918315  1.33363201
  1.37703585  1.40996888  1.47447017  1.46519924  1.4705488   1.51316699
  1.54538844  1.55374633  1.54431128  1.58899825  1.6437012   1.60584679
  1.69281617  1.77201793  1.88576165  1.85219445  1.86241352  1.73604646
  1.79195538  1.83875303  1.84650679  1.80645959  1.75655336  1.7814475
  1.88463191  1.88601331  1.84354001  1.86127622  1.85971188  2.06380012
  2.05678051  2.19082963  2.15944731  2.22499127  2.31664646  2.41354903
  2.39741716  2.27004268  2.27319755  2.30184938  2.31108662  2.241021
  2.21489977  2.17242038  2.12234793  2.14197768  2.21517349  2.13680239
  2.2552277   2.29525905  2.2157694   2.16161398  2.16219879  2.14101707
  2.14609343  1.99116179  2.08413465  2.12711704  2.18123634  2.16980799
  2.21857255  2.09381649  2.10633262  2.04311978  2.00

In [72]:
print returns[0]

[ 1.01132765  1.02895679  1.00316787  1.02132519  0.9826543   0.97559499
  1.0131732   1.04310912  0.97446017  1.01494111  0.99840295  1.04344894
  1.02354792  1.03695408  1.00771292  1.01516955  1.05851542  1.04256533
  1.03254559  1.02391589  1.0457466   0.99371237  1.00365108  1.02898115
  1.02129405  1.00540828  0.99392755  1.02893651  1.03442606  0.97697002
  1.05415796  1.04678698  1.06418881  0.98219966  1.00551728  0.93214876
  1.03220474  1.02611541  1.00421686  0.97831191  0.97237346  1.01417215
  1.05792166  1.00073299  0.97747985  1.00962074  0.99915953  1.10974186
  0.9965987   1.06517424  0.9856756   1.03035219  1.04119351  1.04182881
  0.99331612  0.94687012  1.00138978  1.0126042   1.00401296  0.96968283
  0.98834405  0.98082108  0.97695085  1.00924907  1.03417207  0.96462078
  1.05542174  1.01775047  0.96536789  0.97555909  1.00027054  0.99020362
  1.00237101  0.9278076   1.04669277  1.02062362  1.02544256  0.99476061
  1.02247413  0.94376742  1.00597767  0.96998915  0

In [75]:
market_valueZERO = returns[0] * assets[0]

In [76]:
print market_valueZERO

[ 1.02278361  1.07074525  1.04721594  1.08890683  1.02950436  0.99716392
  1.04921474  1.12678271  1.02574313  1.08431687  1.06494476  1.16135135
  1.16602748  1.22495365  1.19959263  1.22680102  1.35403509  1.3903985
  1.42185228  1.44368954  1.54192217  1.45598661  1.4759179   1.55702031
  1.57829602  1.56214942  1.53493352  1.63497831  1.70028736  1.56886417
  1.78449564  1.85492529  2.00680645  1.81922475  1.87268898  1.61825356
  1.84966484  1.88677281  1.85429326  1.76728094  1.70802587  1.80669444
  1.99379292  1.88739574  1.80202321  1.87918307  1.85814885  2.29028538
  2.04978478  2.33361529  2.12851453  2.29252463  2.41207726  2.51450491
  2.38139311  2.14943559  2.2763568   2.33086235  2.32036092  2.17307958
  2.189083    2.1307557   2.0734296   2.16178899  2.29087055  2.061204
  2.38021635  2.33600098  2.13903264  2.10878217  2.16278375  2.12004285
  2.15118184  1.84741503  2.18144866  2.17098589  2.23673257  2.15843953
  2.26843304  1.97607578  2.11892358  1.98180401  1.95

In [77]:
returns[0] * assets[0]

array([ 1.02278361,  1.07074525,  1.04721594,  1.08890683,  1.02950436,
        0.99716392,  1.04921474,  1.12678271,  1.02574313,  1.08431687,
        1.06494476,  1.16135135,  1.16602748,  1.22495365,  1.19959263,
        1.22680102,  1.35403509,  1.3903985 ,  1.42185228,  1.44368954,
        1.54192217,  1.45598661,  1.4759179 ,  1.55702031,  1.57829602,
        1.56214942,  1.53493352,  1.63497831,  1.70028736,  1.56886417,
        1.78449564,  1.85492529,  2.00680645,  1.81922475,  1.87268898,
        1.61825356,  1.84966484,  1.88677281,  1.85429326,  1.76728094,
        1.70802587,  1.80669444,  1.99379292,  1.88739574,  1.80202321,
        1.87918307,  1.85814885,  2.29028538,  2.04978478,  2.33361529,
        2.12851453,  2.29252463,  2.41207726,  2.51450491,  2.38139311,
        2.14943559,  2.2763568 ,  2.33086235,  2.32036092,  2.17307958,
        2.189083  ,  2.1307557 ,  2.0734296 ,  2.16178899,  2.29087055,
        2.061204  ,  2.38021635,  2.33600098,  2.13903264,  2.10